version: '3.3'
services:
  db:
    container_name: db
    image: mongo:latest
    networks:
      - network1
    ports:
      - 27017:27017
  pt:
    # build: ./server
    image: wqwz111/push-text:latest
    volumes:
      - /ssl-conf:/ssl-conf
    env_file:
      - ./server_config.env
    ports:
      - 443:443
      - 3000:3000
    networks: 
      - network1
    depends_on:
      - db
networks: 
  network1:
    driver: bridge
